services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
