version: '3'

tasks:  
  default:
    cmds:  
      - task: run 
  run: 
    desc: "Run application with defined config"  
    cmds:
      - go run cmd/sso/main.go --config="./config/local.yaml"
  migrate:
    desc: "Making migrations in your postgres database"
    cmds:
      - go run cmd/migrations/main.go --migrations-table="migrations"
  generate:
    aliases:
      - gen  
    desc: "Generate code from proto files"  
    cmds:
      - protoc -I proto proto/sso.proto --go_out=./generated/ --go_opt=paths=source_relative --go-grpc_out=./generated/ --go-grpc_opt=paths=source_relative