env: "local" #dev, prod
postgres:
  user: "postgres"
  password: "admin" # sensitive
  host: "localhost"
  port: 5432
  dbname: "sso" # sensitive
  sslmode: "disable"
token_ttl: 1h
secret: "watafuk" # sensitive
grpc:
  port: 44044
  timeout: 10h