env: "local" #dev, prod
postgres:
  user: "postgres"
  password: "admin"
  host: "localhost"
  port: 5432
  dbname: "sso"
  sslmode: "disable"
token_ttl: 1h
secret: "watafuk"
grpc:
  port: 44044
  timeout: 10h